### ISSUE TITLE
[STORY 3.4] Remove Assets

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#11]
As an investor, I want to remove an asset from my portfolio so that I can keep my portfolio information current.

### Acceptance Criteria:
- [x] Option to delete an asset from the portfolio.
- [x] Asset is removed and no longer displayed in the asset list.
- [x] Confirmation message upon successful asset removal.

### Tasks:
- [x] #87
- [x] #88
- [x] #89
- [ ] #90
- [ ] #91
- [ ] #92
- [ ] #93
- [ ] #94
- [x] #95
- [x] #96

### Linked Issues:
- #7 
- Documentation: Asset Removal Process Documentation

##### Next story:
- #12 

##### Previous story:
- #10
