### ISSUE TITLE
[TASK 1.1.1] Install Django and set up a virtual environment

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#112]
Install Django within a Python virtual environment to ensure an isolated and controlled development environment.

#### Acceptance Criteria:
- [x] A Python virtual environment is created and activated.
- [x] Django is installed within the virtual environment.
- [x] The installation is verified by creating and running a basic Django project.

#### Steps:
1. Create a Python virtual environment using `venv`.
2. Activate the virtual environment.
3. Install Django using `pip install django .`.
4. Create `env.py` file in the root and import os
5. Import os on the `settings.py` file
6. Protect `SECRET_KEY`, by moving it from the settings file and referencing it from the `env.py` file
7. Add dynamic check to the `DEBUG` option on `settings.py` file, by referencing the `env.py` DEVELOPMENT var
8. Create the `DEVELOPMENT` var inside `env.py`
9. Make the `venv` create as selected Python interpreter, so that is auto solected when opening new sessions
10. Verify the installation by creating a basic Django project.

#### Linked Issues:
- #105
- #106

##### Next task:
- #113

**Comment by catapam** [comment]
All set and tested
[Commit](https://github.com/catapam/investnest/commit/7d5c06eb7361f805699c22f2dad4bf7c1dbda768)
