### ISSUE TITLE
[TASK 1.2.2] Install the selected database and set up local development

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#118]
Install the chosen SQL database (MySQL or PostgreSQL) on the local development environment and set up necessary configurations.

#### Acceptance Criteria:
- [x] The selected database is installed on the local machine.
- [x] A local database instance is created and configured for development use.
- [x] The installation is verified by connecting to the database and creating a test table.

#### Steps:
1. Download and install the chosen database (MySQL/PostgreSQL) on the local environment.
2. Set up the initial database instance with appropriate configurations.
3. Verify the installation by creating a connection and a test table.

#### Linked Issues:
- #105
- #106

##### Next task:
- #119

##### Previous task:
- #117

**Comment by catapam** [comment]
Database used is external connection with a Code Institute Postgress setup.
[Commit](https://github.com/catapam/investnest/commit/b9b3dea15bb4a99e719463af090f43f01bc260bb)

Error encountered during initial migrate:
```
django.db.utils.OperationalError: ERROR:  Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'. See more at https://neon.tech/sni
ERROR:  connection is insecure (try using sslmode=require) 
```

- The solution is to change the DB postgress link on the env.py file, the original link copied should have this format:
``postgress://user:password@endpoint_id.hostname/dbname``
the new link:
``postgress://user:password@endpoint_id.hostname/dbname?options=endpoint%3Dendpoint_id&sslmode=require``
