### ISSUE TITLE
[TASK 1.2.3] Configure the database connection in settings.py

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#119]
Configure the Django `settings.py` file to establish a connection with the selected SQL database for the project.

#### Acceptance Criteria:
- [x] The database connection settings in `settings.py` are correctly configured.
- [x] The connection is tested and verified with a successful database connection.
- [x] Any necessary dependencies (e.g., database drivers) are installed.

#### Steps:
1. Open the `settings.py` file and configure the `DATABASES` setting.
2. Ensure that the correct database engine (MySQL/PostgreSQL) is specified.
3. Install any necessary database drivers using `pip`.
4. Test the connection by running `python manage.py migrate` to ensure Django can connect to the database.
5. Document the configuration process.

#### Linked Issues:
- #105
- #106
- Documentation: Database Connection Configuration Documentation

##### Next task:
- #120

##### Previous task:
- #118

**Comment by catapam** [comment]
Database used is external connection with a Code Institute Postgress setup.
[Commit](https://github.com/catapam/investnest/commit/b9b3dea15bb4a99e719463af090f43f01bc260bb)

Error encountered during initial migrate:
```
django.db.utils.OperationalError: ERROR:  Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'. See more at https://neon.tech/sni
ERROR:  connection is insecure (try using sslmode=require) 
```

- The solution is to change the DB postgress link on the env.py file, the original link copied should have this format:
``postgress://user:password@endpoint_id.hostname/dbname``
the new link:
``postgress://user:password@endpoint_id.hostname/dbname?options=endpoint%3Dendpoint_id&sslmode=require``
