### ISSUE TITLE
[STORY 2.2] User Login

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#3]
As a user, I want to log in to my account so that I can access my portfolio.

### Acceptance Criteria:
- [x] Login form includes fields for email and password.
- [x] Successful login redirects user to the dashboard.
- [ ] Error message displayed for incorrect credentials.

### Tasks:
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #54
- [x] #55
- [ ] #56

### Linked Issues:
- #1 
- Documentation

##### Next story:
- #5 

##### Previous story:
- #2
