### ISSUE TITLE
[TASK 2.2.3] Validate user credentials.

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#33]
Implement functionality to validate user credentials (email and password) during the login process.

#### Acceptance Criteria:
- [ ] Email is checked against the database.
- [x] Password is validated against the stored hashed password.
- [x] Login is successful if credentials are correct.

#### Steps:
1. Implement functionality to retrieve the user’s data based on the email.
2. Validate the password against the stored hashed password.
3. Return a success or failure response based on validation.

#### Linked Issues:
- #1
- #3
- Documentation: Credential Validation Documentation

##### Next task:
- #34  

##### Previous task:
- #32

**Comment by catapam** [comment]
[commit](https://github.com/catapam/investnest/commit/b0fb9038b10a86a0378abf78580ac6f7b749df8d)
