### ISSUE TITLE
[STORY 2.3] Password Management

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#5]
As a user, I want to reset my password if I forget it so that I can regain access to my account.

### Acceptance Criteria:
- [x] Forgot password link on the login page
- [ ] Password reset email sent to the user.
- [ ] User can set a new password using the link in the email.

### Tasks:
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [ ] #57
- [x] #58
- [x] #59

### Linked Issues:
- #1 
- Documentation: Password Reset Process Documentation

##### Next story:
- #6  

##### Previous story:
- #3
