### ISSUE TITLE
[STORY 3.1] Portfolio Creation

### ISSUE THREAD

**Issue by catapam** [catapam/investnest#8]
As an investor, I want to create a new investment portfolio so that I can start tracking my investments.

### Acceptance Criteria:
- [x] Form to create a portfolio with fields for name and initial capital.
- [x] User can view a list of their portfolios.
- [ ] Confirmation message upon successful portfolio creation.

### Tasks:
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [ ] #65
- [ ] #66
- [x] #67
- [x] #68

### Linked Issues:
- #7
- Documentation: Portfolio Creation Process Documentation

##### Next story:
- #9
